### ISSUE TITLE
Codec can't decode byte 0xec in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by littlesandra88** [bierschi/chromepass#2]
This is `pip` installed on Fedora 32 Linux and I get

```
➜  ~ chromepass

Traceback (most recent call last):
  File "/usr/local/bin/chromepass", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/chromepass/main.py", line 27, in main
    results = chromepass.get_passwords()
  File "/usr/local/lib/python3.8/site-packages/chromepass/chrome_passwords.py", line 68, in get_passwords
    password = self.os.decrypt_password(encrypted_password=encrypted_password)
  File "/usr/local/lib/python3.8/site-packages/chromepass/chrome_linux.py", line 63, in decrypt_password
    password = decrypted.strip().decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xec in position 0: invalid continuation byte
```
Are there some files I can provide to help debugging?

**Comment by bierschi** [comment]
This error happens due to special characters are included in the password. Right now only utf-8 encoded characters are supported. You can change the appropiate decoding manually in line 63.

I will try to support multiple encodings in the next release version.

**Comment by littlesandra88** [comment]
Very odd. I have gone over all the passwords, and all of them are in ascii. Is it somehow possible to make chromepass output which password that is the issue?
