### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by RandiBam** [bierschi/chromepass#3]
Trying to complete the sudo python3 setup.py install command on Windows 10x64 i avoided sudo command. However, after this i still have an issue to install the downloaded package. Here is the trouble:
C:\Windows\System32\chromepass>python3 setup.py install
Traceback (most recent call last):
  File "C:\Windows\System32\chromepass\setup.py", line 3, in <module>
    from chromepass import __version__, __author__, __email__, __license__, __title__
  File "C:\Windows\System32\chromepass\chromepass\__init__.py", line 10, in <module>
    from chromepass.chrome_linux import ChromeLinux
  File "C:\Windows\System32\chromepass\chromepass\chrome_linux.py", line 4, in <module>
    import secretstorage
ModuleNotFoundError: No module named 'secretstorage'

Maybe my python version is not approprieted one... 

Does somebody has full instruction how to install the chromepass on windows?

**Comment by bierschi** [comment]
I´ve updated the project for the windows environment, replaced `win32crypt `with `pywin32 `package.

Install commands for windows:

with pip:
`pip install chromepass`

from source:
```
git clone https://github.com/bierschi/chromepass
cd chromepass
pip install -r requirements.txt
python setup.py install
```

If you want to use a specific python version:

```
git clone https://github.com/bierschi/chromepass
cd chromepass
py -3.8 -m pip install -r requirements.txt
py -3.8 setup.py install
```
